### ISSUE TITLE
Limpiar todos los componentes que utilicen punteros a managers

### ISSUE THREAD

**Issue by borjacano97** [SeriousGamesStudio/Serious-Train-2-3D#38]
Hay componentes que todavían tienen un puntero a un manager en la constructora. Hay que quitarlos y hacer que utilicen el get instance *dentro* de la constructora, no como parámatro

**Comment by borjacano97** [comment]
Venga ta' luego 👋

**Comment by franlbc97** [comment]
Cara dura
